CREATE TABLE datos_cuenca4 as
SELECT 
        row_number() OVER () as pre_id,          
          his.csa_anio pre_anio,
              avg(his.tmax01) tmax01, 
              avg(his.tmax02) tmax02, 
              avg(his.tmax03) tmax03, 
              avg(his.tmax04) tmax04, 
              avg(his.tmax05) tmax05, 
              avg(his.tmax06) tmax06, 
              avg(his.tmax07) tmax07, 
              avg(his.tmax08) tmax08, 
              avg(his.tmax09) tmax09, 
              avg(his.tmax10) tmax10, 
              avg(his.tmax11) tmax11, 
              avg(his.tmax12) tmax12, 
              avg(his.tmin01) tmin01, 
              avg(his.tmin02) tmin02, 
              avg(his.tmin03) tmin03, 
              avg(his.tmin04) tmin04, 
              avg(his.tmin05) tmin05, 
              avg(his.tmin06) tmin06, 
              avg(his.tmin07) tmin07, 
              avg(his.tmin08) tmin08, 
              avg(his.tmin09) tmin09, 
              avg(his.tmin10) tmin10, 
              avg(his.tmin11) tmin11, 
              avg(his.tmin12) tmin12, 
              avg(his.tmed01) tmed01, 
              avg(his.tmed02) tmed02, 
              avg(his.tmed03) tmed03, 
              avg(his.tmed04) tmed04, 
              avg(his.tmed05) tmed05, 
              avg(his.tmed06) tmed06, 
              avg(his.tmed07) tmed07, 
              avg(his.tmed08) tmed08, 
              avg(his.tmed09) tmed09, 
              avg(his.tmed10) tmed10, 
              avg(his.tmed11) tmed11, 
              avg(his.tmed12) tmed12, 
              avg(his.pre01) pre01, 
              avg(his.pre02) pre02, 
              avg(his.pre03) pre03, 
              avg(his.pre04) pre04, 
              avg(his.pre05) pre05, 
              avg(his.pre06) pre06, 
              avg(his.pre07) pre07, 
              avg(his.pre08) pre08, 
              avg(his.pre09) pre09, 
              avg(his.pre10) pre10, 
              avg(his.pre11) pre11, 
              avg(his.pre12) pre12,
              avg(his.tmax_anual) tmax_anual,
              avg(his.tmin_anual) tmin_anual,
              avg(his.tmed_anual) tmed_anual,
              avg(his.pre_anual) pre_anual,
                lug.id_cue4,
        'CLIMATE SA' pre_fuente,
        '' pre_modelo,
        '' prercp,
  FROM lugar lug
  INNER JOIN (
        SELECT *
      FROM historico
      )  as his ON his.lug_id = lug.lug_id
  GROUP BY lug.id_cue4,csa_anio
